---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warden
  namespace: bitwarden
  labels:
    app: bitwarden
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: bitwarden
  namespace: bitwarden
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: bitwarden
  namespace: bitwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bitwarden
subjects:
- kind: ServiceAccount
  name: warden
