---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secrets
  namespace: bitwarden
  labels:
    app: bitwarden
type: Opaque
data:
  SMTP_USERNAME: <base64_encoded_smtp_username>
  SMTP_PASSWORD: <base64_encoded_smtp_password>
  ADMIN_TOKEN: <base64_encoded_token>
